### ISSUE TITLE
[model feedback]4xFrankendata_FullDegradation

### ISSUE THREAD

**Issue by FNsi** [terrainer/AI-Upscaling-Models#1]
It's not perfect, but still amazing.

Texture problem:

Origin:
![image](https://github.com/terrainer/AI-Upscaling-Models/assets/125447286/3b707eda-7aa4-4bdc-9ce5-a38ade244386)

4xFrankendata:
![image](https://github.com/terrainer/AI-Upscaling-Models/assets/125447286/73e6cb81-fd56-4a05-a468-799325108632)

Something wrong...

The great moment:
![image](https://github.com/terrainer/AI-Upscaling-Models/assets/125447286/38b7abe6-8101-4db2-a029-2861456f705c)

**Comment by FNsi** [comment]
For the ladder?(sofa?), it supposed to be kind like that.
![image](https://github.com/terrainer/AI-Upscaling-Models/assets/125447286/19dbdd0a-7b17-40c3-8f2c-685d5d9f6aff)

(But model in this photo obviously removed more details in wall, that's bad)

Meanwhile if low res pic show the hair cross skin, model might stuck the hair into the skin...

![image](https://github.com/terrainer/AI-Upscaling-Models/assets/125447286/807e9e2c-2a2f-4f4f-9fe3-a3c7ebf96428)

**Comment by terrainer** [comment]
This was an early model. I'm working on higher quality, more efficient models but nothing as of yet has been quite up to scratch for release. In the meantime, you might be able to try [Frankenfixer](https://github.com/terrainer/AI-Upscaling-Models/tree/main/1xFrankenfixer_SRFormerLight) on the upscaled image.
